#! /usr/local/bin/perl

use strict;
use feature 'unicode_strings';

use LWP::UserAgent;

my $Progname = "lwp-debug";

if (not binmode(STDOUT, ":utf8")) {
    die "$Progname: unable to turn on utf8 for STDOUT: $!\n";
}

my $ua = LWP::UserAgent->new;

#
# XXX chess.com recommend putting contact details into the User-Agent string.
#
#$ua->agent('@skelos/0.10');

$ua->default_header('Accept-Encoding' => scalar HTTP::Message::decodable());

$ua->add_handler("request_send",  sub { shift->dump; return });
$ua->add_handler("response_done", sub { shift->dump; return });

$ua->get($ARGV[0]);
